server:
  port: 80
  servlet:
    context-path: /mytran

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #mysql\u9A71\u52A8\u7C7B
    url: jdbc:mysql://localhost:3306/springdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: xu123456

  # 指定 mybatis 查找 mapper 的路径
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 配置 mybatis 输出 sql 语句的日志信息

