#\u914D\u7F6E\u7AEF\u53E3\u53F7
server:
  port: 80
  servlet:
    context-path: /myboot

#\u914D\u7F6E\u89C6\u56FE\u89E3\u91CA\u5668
#/ = src/main/webapp
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
